---
- name: Ensure NATS JetStream directory is present or leaf
  ansible.builtin.file:
    mode: "0755"
    path: "{{ nats_leaf_store_dir }}"
    state: directory

- name: Create nats-leaf configuration file.
  ansible.builtin.template:
    src: nats-leaf.conf.j2
    dest: '{{ nats_leaf_config_file_path }}'
    mode: "0644"
    backup: false
  notify:
    - Start nats-leaf

- name: Ensure nats-leaf service file is available.
  ansible.builtin.template:
    src: nats-leaf.service.j2
    dest: '{{ nats_leaf_service_file_path }}'
    mode: "0644"
    backup: false
  notify:
    - Reload daemon nats-leaf

- name: Ensure nats-leaf service is started and enabled on boot.
  ansible.builtin.service:
    name: nats-leaf
    state: started
    enabled: true