---
- name: Install wasmcloud package.
  ansible.builtin.apt:
    state: present
    deb: "https://github.com/wasmCloud/wasmCloud/releases/download/{{ wasmcloud_version }}/wasmcloud-{{ arch}}"

- name: Ensure wasmcloud service file is available.
  ansible.builtin.template:
    src: wasmcloud-host.service.j2
    dest: /etc/systemd/system/wasmcloud-host.service
    mode: "0644"
    backup: false
  notify:
    - Reload daemon wasmcloud-host
  
- name: Ensure wasmcloud service is started and enabled on boot.
  ansible.builtin.service:
    name: wasmcloud-host
    state: started
    enabled: true

- name: Create or update wasmcloud env file (/etc/wasmcloud/wasmcloud-host.env)
  ansible.builtin.template:
    src: wasmcloud-host.env.j2
    dest: /etc/wasmcloud/wasmcloud-host.env
    mode: "0644"
    backup: false
  notify:
    - Restart wasmcloud-host