---
- name: Install wasmcloud package.
  ansible.builtin.get_url:
    dest: "{{ wasmcloud_file_path }}"
    mode: "0755"
    url: "https://github.com/wasmCloud/wasmCloud/releases/download/{{ wasmcloud_version }}/wasmcloud-{{ arch }}"

- name: Ensure wasmcloud service file is available.
  ansible.builtin.template:
    src: wasmcloud-host.service.j2
    dest: '{{ wasmcloud_service_file_path }}'
    mode: "0644"
    backup: false
  notify:
    - Reload daemon wasmcloud-host

- name: Ensure wasmcloud directory exists
  ansible.builtin.file:
    path: /etc/wasmcloud
    state: directory
    mode: "0755"
    owner: root
    group: root
  become: true

- name: 'Create or update wasmcloud env file ({{ wasmcloud_environment_file_path }})'
  ansible.builtin.template:
    src: wasmcloud-host.env.j2
    dest: '{{ wasmcloud_environment_file_path }}'
    mode: "0644"
    backup: false
  notify:
    - Start wasmcloud-host

- name: Ensure wasmcloud service is started and enabled on boot.
  ansible.builtin.service:
    name: wasmcloud-host
    state: started
    enabled: true
