---
# TODO: separate handlers for different files
- name: Restart nats-leaf
  ansible.builtin.service:
    name: nats-leaf
    state: restarted

- name: Start nats-leaf
  ansible.builtin.service:
    name: nats-leaf
    state: started

- name: Reload nats-leaf
  ansible.builtin.service:
    name: nats-leaf
    state: reloaded

- name: Reload daemon nats-leaf
  ansible.builtin.systemd:
    state: stopped
    daemon_reload: true
    name: nats-leaf

- name: Restart wasmcloud-host
  ansible.builtin.service:
    name: wasmcloud-host
    state: restarted

- name: Start wasmcloud-host
  ansible.builtin.service:
    name: wasmcloud-host
    state: started

- name: Reload wasmcloud-host
  ansible.builtin.service:
    name: wasmcloud-host
    state: reloaded

- name: Reload daemon wasmcloud-host
  ansible.builtin.systemd:
    state: stopped
    daemon_reload: true
    name: wasmcloud-host
