---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install ansible
        run: |
          python -m pip install --upgrade ansible ansible-lint
      - name: create ansible.cfg with correct roles_path
        run: printf '[defaults]\nroles_path=../' > ansible.cfg
      - uses: ansible/ansible-lint@main
        with:
          args: tests/test.yaml
        name: ansible-lint
      - run: ansible-playbook tests/test.yaml -i tests/inventory --syntax-check
        name: basic role syntax check
      - run: ansible-playbook tests/test.yaml -i tests/inventory --become -v
        name: install wasmcloud and start its service
        #TODO: clarify the playbook to run expected CI check here
        # - run: systemctl is-active --quiet wasmcloud-host
        #   name: wasmcloud is running